

trigger:
- master
resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build

    pool:
      vmImage: ubuntu-latest
    steps:
      - task: DockerInstaller@0
        inputs:
          dockerVersion: '17.09.0-ce'
      - task: Docker@2
        inputs:
          containerRegistry: '7797-docker-kuber'
          repository: '7797/Hello-app-Docker-Image'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: '$(tag)'
